# This docker-compose file is for internal testing only.
# Please refer to the documentation on https://docs.facilmap.org/developers/server/docker.html for how to start FacilMap with docker.

version: "2"
services:
    facilmap:
        build: .
        image: facilmap/facilmap
        ports:
            - "127.0.0.1:8080:8080"
        environment:
            DB_TYPE: mysql
            DB_HOST: mysql
            # DB_TYPE: postgres
            # DB_HOST: postgres
            DB_NAME: facilmap
            DB_USER: facilmap
            DB_PASSWORD: facilmap
        links:
            - mysql
        depends_on:
            mysql:
                condition: service_healthy
        restart: on-failure

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: facilmap
            MYSQL_USER: facilmap
            MYSQL_PASSWORD: facilmap
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
        ports:
            - "127.0.0.1:40830:3306"

    # postgres:
    #     image: postgis/postgis:16-3.4
    #     environment:
    #         POSTGRES_USER: facilmap
    #         POSTGRES_PASSWORD: facilmap
    #         POSTGRES_DB: facilmap
    #     healthcheck:
    #         test: pg_isready -d $$POSTGRES_DB
    #     ports:
    #         - "127.0.0.1:40831:5432"

    # phpmyadmin:
    #     image: phpmyadmin
    #     links:
    #         - mysql:db
    #     ports:
    #         - 127.0.0.1:8090:80