version: "2"
services:
    facilmap:
        build: .
        image: facilmap/facilmap
        ports:
            - "127.0.0.1:8080:8080"
        environment:
            DB_TYPE: mariadb
            DB_HOST: mariadb
            DB_NAME: facilmap
            DB_USER: facilmap
            DB_PASSWORD: facilmap
        links:
            - mysql
        restart: on-failure
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: facilmap
            MYSQL_USER: facilmap
            MYSQL_PASSWORD: facilmap
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
    phpmyadmin:
        image: phpmyadmin
        links:
            - mysql:db
        ports:
            - 127.0.0.1:8090:80