services:
    facilmap-mysql:
        image: facilmap-ci
        links:
            - mysql
        ports:
            - "8080:8080"
        environment:
            DB_TYPE: mysql
            DB_HOST: mysql
            DB_NAME: facilmap
            DB_USER: facilmap
            DB_PASSWORD: facilmap

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: facilmap
            MYSQL_USER: facilmap
            MYSQL_PASSWORD: facilmap
            MYSQL_RANDOM_ROOT_PASSWORD: "true"


    facilmap-postgres:
        image: facilmap-ci
        links:
            - postgres
        ports:
            - "8081:8080"
        environment:
            DB_TYPE: postgres
            DB_HOST: postgres
            DB_NAME: facilmap
            DB_USER: facilmap
            DB_PASSWORD: facilmap

    postgres:
        image: postgis/postgis:16-3.4
        environment:
            POSTGRES_USER: facilmap
            POSTGRES_PASSWORD: facilmap
            POSTGRES_DB: facilmap
