import "./styles.scss";

// Bootstrap import, see https://getbootstrap.com/docs/5.3/customize/optimize/#lean-javascript
import 'bootstrap/js/dist/alert';
import 'bootstrap/js/dist/button';
import 'bootstrap/js/dist/carousel';
// import 'bootstrap/js/dist/collapse';
import 'bootstrap/js/dist/dropdown';
import 'bootstrap/js/dist/modal';
// import 'bootstrap/js/dist/offcanvas';
import 'bootstrap/js/dist/popover';
// import 'bootstrap/js/dist/scrollspy';
import 'bootstrap/js/dist/tab';
import 'bootstrap/js/dist/toast';
import 'bootstrap/js/dist/tooltip';

import { registerDeobfuscationHandlers } from "../utils/obfuscate";

registerDeobfuscationHandlers();

export { default as BoxSelection } from "./utils/box-selection";
export * from "./utils/box-selection";
export * from "./utils/draw";
export * from "./utils/files";
export { default as FmHeightgraph } from "./utils/heightgraph";
export * from "./utils/heightgraph";
export * from "./utils/search";
export { default as SelectionHandler } from "./utils/selection";
export * from "./utils/selection";
export { default as storage } from "./utils/storage";
export * from "./utils/storage";
export * from "./utils/ui";
export * from "./utils/utils";
export * from "./utils/vue";
export * from "./utils/zoom";

export * from "../utils/obfuscate";

export { default as AboutDialog } from "./components/about-dialog.vue";
export { default as ClickMarkerTab } from "./components/click-marker-tab.vue";
export { default as ClientContext } from "./components/client-provider.vue";
export { default as EditFilterDialog } from "./components/edit-filter-dialog.vue";
export { default as EditLineDialog } from "./components/edit-line-dialog.vue";
export { default as EditMarkerDialog } from "./components/edit-marker-dialog.vue";
export { default as EditTypeDialog } from "./components/edit-type-dialog/edit-type-dialog.vue";
export * from "./components/facil-map.vue";
export { default as FacilMap } from "./components/facil-map.vue";
export { default as FileResults } from "./components/file-results.vue";
export { default as HistoryDialog } from "./components/history-dialog/history-dialog.vue";
export { default as ImportTab } from "./components/import-tab.vue";
export * from "./components/leaflet-map/leaflet-map.vue";
export { default as LeafletMap } from "./components/leaflet-map/leaflet-map.vue";
export { default as Legend } from "./components/legend/legend.vue";
export { default as LineInfo } from "./components/line-info/line-info.vue";
export { default as ManageBookmarksDialog } from "./components/manage-bookmarks-dialog.vue";
export { default as ManageTypesDialog } from "./components/manage-types-dialog.vue";
export { default as ManageViewsDialog } from "./components/manage-views-dialog.vue";
export { default as MarkerInfo } from "./components/marker-info/marker-info.vue";
export { default as MultipleInfo } from "./components/multiple-info/multiple-info.vue";
export { default as OpenMapDialog } from "./components/open-map-dialog.vue";
export { default as PadSettingsDialog } from "./components/pad-settings-dialog/pad-settings-dialog.vue";
export { default as RouteForm } from "./components/route-form/route-form.vue";
export { default as SaveViewDialog } from "./components/save-view-dialog.vue";
export * from "./components/search-box/search-box.vue";
export { default as SearchBox } from "./components/search-box/search-box.vue";
export { default as SearchForm } from "./components/search-form/search-form.vue";
export { default as SearchResultInfo } from "./components/search-result-info.vue";
export { default as SearchResults } from "./components/search-results/search-results.vue";
export { default as Toolbox } from "./components/toolbox/toolbox.vue";
export { default as ColourPicker } from "./components/ui/colour-picker.vue";
export { default as ElevationPlot } from "./components/ui/elevation-plot.vue";
export { default as ElevationStats } from "./components/ui/elevation-stats.vue";
export { default as FieldInput } from "./components/ui/field-input.vue";
export { default as ModalDialog } from "./components/ui/modal-dialog.vue";
export { default as Icon } from "./components/ui/icon.vue";
export { default as Picker } from "./components/ui/picker.vue";
export { default as PrerenderedList } from "./components/ui/prerendered-list.vue";
export { default as RouteMode } from "./components/ui/route-mode.vue";
export { default as ShapePicker } from "./components/ui/shape-picker.vue";
export { default as Sidebar } from "./components/ui/sidebar.vue";
export { default as SizePicker } from "./components/ui/size-picker.vue";
export { default as SymbolPicker } from "./components/ui/symbol-picker.vue";
export { default as Toast } from "./components/ui/toasts/toast.vue";
export * from "./components/ui/toasts/toasts.vue";
export { default as WidthPicker } from "./components/ui/width-picker.vue";